test: fix multi-line bash, exit 1

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,7 +12,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Failed Step
-        run: echo "I will fail"
-             exit 0
+        run: |
+          echo "I will fail"
+          exit 1
       - name: Say Goodbye
         run: echo "Goodbye!"
